import {readBarcodes,prepareZXingModule} from 'zxing-wasm/reader';
import {createWorker} from 'tesseract.js';
import {compare,csv,RULE,extractPrint} from './compare.mjs';
import {selectOCR,inspect,nearbyRegion} from './inspection.mjs';
import {readPrintedSerial} from './paddle-reader.mjs';
import {saveRecordWithPhoto,listRecords,getPhoto} from './storage.mjs';
import {syncRecords} from './sync.mjs';
import {usesProfile,SHIFT_LABELS,isShiftCode,DEFAULT_MODEL,getModelProfile,isModelCode,comparePositions} from './serial-profile.mjs';
import {normalizeInspectorName} from './inspector-roster.mjs';
const $=s=>document.querySelector(s);const base=new URL('./',location.href);const asset=p=>new URL(p,base).href;
prepareZXingModule({overrides:{locateFile:path=>path.endsWith('.wasm')?asset('vendor/zxing_reader.wasm'):path}});
let selectedModel=DEFAULT_MODEL,worker=null,busy=false,saving=false,saved=false,records=[],limit=50,originalCode='',originalOCR='',codeSource='manual',printSource='manual',format='',confidence=null,photoBase=null,cropMode=false,crop=null,start=null,storageReady=false,ocrReliable=false,ocrAttempts=[],codePosition=null,captureSource='foto',inspector='',inspectorShift='',syncBusy=false,nativeCapturePending=false,processingUpload=false,nativeReturnTimer=null,photoUrl=null,visualAssessment=null,visualDecision='';
let inspectors=[],rosterOnline=false,managerPassword='';
const canvas=$('#photo'),ctx=canvas.getContext('2d',{willReadFrequently:true});
function message(text,error=false){for(const selector of ['#scan-message','#capture-feedback']){const node=$(selector);node.textContent=text;node.classList.toggle('error',error);}}
function setBusy(value){busy=value;for(const s of ['#native-trigger','#native-file','#file','#new','#crop-start','#crop-read','#detail-read','#invert','#inspector-input','#inspector-submit','#model-select','#tab-management'])$(s).disabled=value;for(const choice of document.querySelectorAll('input[name="shift"]'))choice.disabled=value;$('#qr').disabled=value;$('#ocr').disabled=value;$('#confirmed').disabled=value;$('#progress').hidden=!value;update();}
function positionRows(profile){const fragment=document.createDocumentFragment();for(const item of profile.positions){const row=document.createElement('div');row.className='position-row '+(!item.valid||!item.printValid||!item.match?'position-error':'position-match');const number=document.createElement('span'),meaning=document.createElement('span'),code=document.createElement('strong'),print=document.createElement('strong');number.textContent=String(item.position);const hint=item.expected?'esperado '+item.expected:item.valid?item.decoded:item.rule;meaning.textContent=item.meaning+(hint?' · '+hint:'');code.textContent=item.code;print.textContent=item.print;row.append(number,meaning,code,print);fragment.append(row);}return fragment;}
function renderPositions(profile){const panel=$('#position-details'),list=$('#position-list');panel.hidden=!profile;list.replaceChildren(...(profile?[positionRows(profile)]:[]));}
function canReviewOCR(result){return !!result.ocrAmbiguity;}
function renderVisualPanel(){const panel=$('#visual-panel');panel.hidden=!visualAssessment;if(!visualAssessment)return;panel.className='visual-panel manual';$('#visual-title').textContent='Conferência visual da tampografia';$('#visual-reason').textContent='Amplie a foto, examine toda a impressão e escolha uma resposta antes de registrar.';$('#visual-review').hidden=false;$('#visual-review legend').textContent='Ao conferir a foto e a peça, há falha visual na impressão?';}
function withVisualStatus(result){return visualDecision==='defect'?{...result,status:'DIVERGENTE',reason:['Falha visual identificada pelo inspetor ao conferir a foto e a peça.',result.reason].filter(Boolean).join(' ')}:result;}
function update(){
  const inspection=withVisualStatus(inspect($('#qr').value,$('#ocr').value,ocrReliable,$('#confirmed').checked,inspectorShift,selectedModel));
  const result=!inspectorShift&&inspection.status==='COINCIDE'?{...inspection,status:'PENDENTE',reason:'Selecione seu turno para validar o código 2D.'}:inspection;
  $('#qr-series').textContent=result.code.serial||'Não identificado';
  $('#print-series').textContent=result.print.serial||'Não identificado';
  renderPositions(result.profile);
  $('#position-details h3').textContent='Validação por posição · '+getModelProfile(selectedModel).secCode;
  const shiftStatus=$('#shift-check');
  shiftStatus.className='shift-check '+({match:'match',mismatch:'mismatch'}[result.shiftCheck.status]||'pending');
  shiftStatus.textContent=!inspectorShift?'Selecione seu turno acima para validar a letra do código 2D.':result.shiftCheck.status==='unread'?`${SHIFT_LABELS[inspectorShift]} (${inspectorShift}) selecionado. Leia o código 2D para conferir o turno.`:result.shiftCheck.status==='match'?`Código 2D correto para ${SHIFT_LABELS[inspectorShift]}: posição 7 = ${result.shiftCheck.actual}.`:result.shiftCheck.status==='mismatch'?`Código 2D incorreto para ${SHIFT_LABELS[inspectorShift]}: esperado ${inspectorShift}, lido ${result.shiftCheck.actual} na posição 7.`:'Este formato de código 2D não permite validar o turno.';
  const hasData=!!($('#qr').value.trim()||$('#ocr').value.trim()),preview=hasData&&!$('#confirmed').checked;
  $('#confirmed-label').textContent='Conferi o código 2D, a série e a impressão na foto e na peça; confirmo este registro.';
  renderVisualPanel();
  const ambiguity=result.ocrAmbiguity,reviewOCR=canReviewOCR(result);$('#i-review').hidden=!reviewOCR;if(ambiguity){$('#i-review strong').textContent=`Confira ${ambiguity.read} / ${ambiguity.expected} na posição ${ambiguity.position}`;$('#i-review p').textContent=`O OCR leu ${ambiguity.read}, mas o padrão exige ${ambiguity.expected} nesta posição. Confira a foto e a peça antes de corrigir. Outras divergências continuarão visíveis.`;$('#i-correct').textContent=`Corrigir OCR: ${ambiguity.read} → ${ambiguity.expected}`;}$('#i-correct').disabled=!reviewOCR||!$('#confirmed').checked||busy||saved;
  const style={COINCIDE:'match',DIVERGENTE:'mismatch',PENDENTE:'pending'}[result.status];
  $('#result').className='result '+(preview&&result.status==='COINCIDE'?'pending':style);
  $('#result .result-symbol').textContent=preview?'?':{COINCIDE:'✓',DIVERGENTE:'≠',PENDENTE:'!'}[result.status];
  $('#result strong').textContent=preview?{COINCIDE:'Prévia: séries coincidem',DIVERGENTE:'Prévia: divergência detectada',PENDENTE:'Prévia: leitura pendente'}[result.status]:visualDecision==='defect'?'Divergência na impressão confirmada':{COINCIDE:'Os 14 caracteres coincidem',DIVERGENTE:result.partCheck.status==='mismatch'?'SEC CODE do código 2D incorreto':'Série ou turno do código 2D divergente',PENDENTE:!inspectorShift?'Turno não informado':result.rawComparison==='COINCIDE'?'Séries coincidem · confira OCR':'Leitura pendente'}[result.status];
  $('#result p').textContent=(result.status==='PENDENTE'?result.reason:result.status==='DIVERGENTE'?result.reason||'Os valores após + e : são diferentes. Confira a peça antes de registrar.':'Os 14 caracteres após + e : coincidem; a letra do código 2D corresponde ao turno selecionado.')+(preview?' Confira a peça, marque a confirmação e toque em Registrar.':'');
  $('#confirmed').disabled=busy||saving||saved;
  for(const selector of ['#qr','#ocr','#crop-start','#crop-read','#detail-read'])$(selector).disabled=busy||saved||(selector==='#crop-read'&&!crop);
  for(const choice of document.querySelectorAll('input[name="visual-decision"]'))choice.disabled=busy||saving||saved;
  $('#save').disabled=busy||saving||saved||!storageReady||!inspector||!inspectorShift||!hasData||!photoBase||!$('#confirmed').checked||!visualDecision;
  $('#save').textContent=saved?'Comparação registrada':photoBase&&!visualDecision?'Avalie a foto para registrar':!$('#confirmed').checked?'Confirme a leitura para registrar':result.status==='PENDENTE'?'Registrar leitura pendente':'Registrar comparação';
  return result;
}
for(const id of ['#qr','#ocr'])$(id).addEventListener('input',()=>{$('#confirmed').checked=false;saved=false;ocrReliable=false;$('#save-message').textContent='';update();});$('#confirmed').addEventListener('change',()=>update());
for(const choice of document.querySelectorAll('input[name="visual-decision"]'))choice.addEventListener('change',()=>{visualDecision=choice.value;$('#confirmed').checked=false;$('#save-message').textContent='Confira a foto e confirme novamente o registro.';update();});
$('#i-correct').onclick=()=>{const result=inspect($('#qr').value,$('#ocr').value,ocrReliable,$('#confirmed').checked,inspectorShift,selectedModel);const ambiguity=result.ocrAmbiguity;if(!$('#confirmed').checked||!ambiguity)return;const text=$('#ocr').value,serial=result.print.serial,index=text.indexOf(serial);if(index<0||text.indexOf(serial,index+1)>=0)return;const corrected=serial.slice(0,ambiguity.index)+ambiguity.expected+serial.slice(ambiguity.index+1);$('#ocr').value=text.slice(0,index)+corrected+text.slice(index+serial.length);ocrReliable=false;saved=false;$('#confirmed').checked=false;$('#save-message').textContent='Correção manual do OCR aplicada. O texto original continua guardado no registro.';update();};
function clearReadings(){ocrReliable=false;ocrAttempts=[];codePosition=null;originalCode='';originalOCR='';codeSource='manual';printSource='manual';format='';confidence=null;saved=false;visualAssessment=null;visualDecision='';for(const choice of document.querySelectorAll('input[name="visual-decision"]'))choice.checked=false;$('#qr').value='';$('#ocr').value='';$('#confirmed').checked=false;$('#code-format').textContent='Aguardando leitura';$('#confidence').textContent='Leitura OCR';$('#save-message').textContent='';update();}
function setPhoto(image,width,height){const scale=Math.min(1,2560/Math.max(width,height));canvas.width=Math.round(width*scale);canvas.height=Math.round(height*scale);ctx.drawImage(image,0,0,canvas.width,canvas.height);photoBase=ctx.getImageData(0,0,canvas.width,canvas.height);canvas.hidden=false;$('#camera-empty').hidden=true;$('#crop-tools').hidden=false;crop=null;cropMode=false;canvas.classList.remove('selecting');$('#crop-read').disabled=true;}
async function loadPhoto(event){if(processingUpload)return;const file=event.target.files?.[0];if(!file){if(event.target.id==='native-file'){nativeCapturePending=false;message('Nenhuma foto voltou da câmera. Se ela salvou a imagem, toque em Escolher foto para selecioná-la.',true);}return;}processingUpload=true;nativeCapturePending=false;clearTimeout(nativeReturnTimer);message('Foto recebida. Abrindo imagem…');clearReadings();captureSource=event.target.id==='native-file'?'câmera do celular':'foto';photoBase=null;canvas.hidden=true;$('#camera-empty').hidden=false;$('#crop-tools').hidden=true;let image=null,url=null;try{try{image=await createImageBitmap(file);}catch{url=URL.createObjectURL(file);image=new Image();image.src=url;await image.decode();}setPhoto(image,image.width,image.height);image?.close?.();image=null;if(url){URL.revokeObjectURL(url);url=null;}message('Foto carregada. Iniciando leitura…');await readPhoto(false);}catch(error){message('Não foi possível abrir ou ler esta foto. Se ela foi salva, tente Escolher foto. '+error.message,true);}finally{image?.close?.();if(url)URL.revokeObjectURL(url);event.target.value='';processingUpload=false;}}
function checkNativeReturn(){if(!nativeCapturePending||document.hidden)return;clearTimeout(nativeReturnTimer);nativeReturnTimer=setTimeout(()=>{if(!nativeCapturePending||document.hidden)return;const input=$('#native-file');if(input.files?.length)loadPhoto({target:input});else{nativeCapturePending=false;message('A câmera não entregou a foto ao aplicativo. Se a imagem foi salva, toque em Escolher foto e selecione-a.',true);}},2500);}
$('#native-trigger').onclick=()=>{nativeCapturePending=true;message('Abrindo a câmera do celular. Depois da foto, aguarde o retorno ao aplicativo…');$('#native-file').click();setTimeout(checkNativeReturn,500);};
$('#file').onchange=loadPhoto;$('#native-file').onchange=loadPhoto;$('#native-file').oninput=loadPhoto;
async function ocrWorker(){if(!worker){worker=await createWorker('eng',1,{workerPath:asset('vendor/worker.min.js'),corePath:asset('vendor/'),langPath:asset('vendor/'),logger:info=>{if(info.status==='recognizing text')$('#progress').value=info.progress;}});}return worker;}
function preprocessOCR(context,width,height,invert){const image=context.getImageData(0,0,width,height),data=image.data,hist=new Uint32Array(256);for(let i=0;i<data.length;i+=4){const g=Math.round(.299*data[i]+.587*data[i+1]+.114*data[i+2]);data[i]=g;hist[g]++;}const cutoff=width*height*.02;let low=0,high=255,sum=0;while(low<254&&(sum+=hist[low])<cutoff)low++;sum=0;while(high>low&&(sum+=hist[high])<cutoff)high--;for(let i=0;i<data.length;i+=4){let v=Math.max(0,Math.min(255,(data[i]-low)*255/Math.max(1,high-low)));if(invert)v=255-v;data[i]=data[i+1]=data[i+2]=v;}context.putImageData(image,0,0);}
async function readPhoto(selectionOnly,detailed=false){if(busy||!photoBase)return;setBusy(true);saved=false;$('#confirmed').checked=false;$('#save-message').textContent='';ctx.putImageData(photoBase,0,0);const problems=[];try{
if(!selectionOnly){$('#qr').value='';originalCode='';format='';codeSource=captureSource;$('#code-format').textContent='Procurando código';message('Lendo QR Code / Data Matrix…');try{const codes=(await readBarcodes(photoBase,{formats:['QRCode','DataMatrix'],tryHarder:true,tryInvert:true,maxNumberOfSymbols:8})).filter(c=>c.isValid!==false);if(codes.length===1){originalCode=codes[0].text;$('#qr').value=originalCode;format=codes[0].format;codePosition=codes[0].position;$('#code-format').textContent=format;}else{problems.push(codes.length?'Mais de um código na foto. Fotografe uma peça por vez.':'Código não encontrado. Aproxime a câmera ou use um leitor USB.');$('#code-format').textContent='Não identificado';}}catch{problems.push('Falha ao iniciar o leitor de código. Tente reabrir o aplicativo com internet.');}}
$('#ocr').value='';originalOCR='';confidence=null;ocrReliable=false;ocrAttempts=[];printSource=(detailed?'OCR detalhado':'OCR rápido')+' · '+captureSource;$('#confidence').textContent='Lendo…';message('Localizando e reconhecendo a linha da série…');
try{
  const region=selectionOnly&&crop?crop:nearbyRegion(codePosition,canvas.width,canvas.height,selectedModel);
  ocrAttempts=await readPrintedSerial(canvas,region,text=>message(text),$('#invert').checked,detailed);
  const best=selectOCR(ocrAttempts,usesProfile($('#qr').value,selectedModel)?selectedModel:false);originalOCR=best.text;confidence=best.confidence;ocrReliable=best.reliable;
  $('#ocr').value=originalOCR;const bestSerial=extractPrint(originalOCR).serial,agreements=bestSerial?ocrAttempts.filter(attempt=>extractPrint(attempt.text).serial===bestSerial).length:0;$('#confidence').textContent='OCR · '+agreements+'/'+ocrAttempts.length+' leituras da mesma série · score '+confidence+'/100'+(ocrReliable?'':' · revisar');
  if(!ocrReliable)problems.push(compare($('#qr').value,$('#ocr').value,selectedModel).status==='COINCIDE'?'As séries exibidas coincidem. O OCR não confirmou a série com confiança em todas as tentativas. Confira a peça e marque a conferência manual para concluir.':'O OCR não confirmou a série com confiança. Confira a peça ou selecione a linha da série para ler novamente.');
}catch{worker?.terminate();worker=null;$('#confidence').textContent='OCR indisponível';problems.push('Falha no reconhecimento da tampografia. A tentativa será registrada como pendente.');}
if(!selectionOnly)visualAssessment={status:'manual',reason:'Foto disponível para conferência visual pelo inspetor.'};
message(problems.length?problems.join(' '):inspectorShift?'As duas leituras foram comparadas automaticamente.':'Séries lidas. Selecione seu turno para validar o código 2D.',problems.length>0&&compare($('#qr').value,$('#ocr').value,selectedModel).status!=='COINCIDE');
}finally{setBusy(false);crop=null;$('#crop-read').disabled=true;update();}
$('#save-message').textContent='Leitura pronta, ainda não registrada. Amplie a foto, avalie a impressão e confirme antes de registrar.';
}
$('#crop-read').onclick=()=>readPhoto(true,true);$('#detail-read').onclick=()=>readPhoto(true,true);
$('#crop-start').onclick=()=>{cropMode=true;crop=null;canvas.classList.add('selecting');ctx.putImageData(photoBase,0,0);$('#crop-read').disabled=true;message('Arraste sobre a linha inteira, incluindo NÚMERO DE SÉRIE e todos os caracteres.');};
function point(event){const r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(event.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height,(event.clientY-r.top)*canvas.height/r.height))};}
canvas.onpointerdown=e=>{if(!cropMode||busy)return;start=point(e);canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!start)return;const p=point(e);crop={x:Math.round(Math.min(start.x,p.x)),y:Math.round(Math.min(start.y,p.y)),w:Math.round(Math.abs(p.x-start.x)),h:Math.round(Math.abs(p.y-start.y))};ctx.putImageData(photoBase,0,0);ctx.strokeStyle='#28f4c0';ctx.lineWidth=Math.max(2,canvas.width/350);ctx.strokeRect(crop.x,crop.y,crop.w,crop.h);};canvas.onpointerup=()=>{if(!start)return;start=null;cropMode=false;canvas.classList.remove('selecting');$('#crop-read').disabled=!crop||crop.w<30||crop.h<8;};canvas.onpointercancel=()=>{start=null;crop=null;cropMode=false;canvas.classList.remove('selecting');ctx.putImageData(photoBase,0,0);};
$('#new').onclick=()=>{clearReadings();photoBase=null;canvas.hidden=true;$('#camera-empty').hidden=false;$('#crop-tools').hidden=true;message('Pronto para a próxima peça.');$('#native-trigger').focus();};
function badge(status){const b=document.createElement('span');b.className='badge '+{COINCIDE:'match',DIVERGENTE:'mismatch',PENDENTE:'pending'}[status];b.textContent=status;return b;}
function renderHistory(){const visible=records.filter(record=>record.syncState==='synced'||record.inspector===inspector);$('#count').textContent=visible.length;$('#empty-history').hidden=visible.length>0;$('#export').disabled=!visible.length;$('#more').hidden=visible.length<=limit;const body=$('#history');body.replaceChildren();for(const record of visible.slice(0,limit)){const tr=document.createElement('tr');const values=[new Date(record.date).toLocaleString('pt-BR'),record.inspector||'Registro antigo',record.shift?`${SHIFT_LABELS[record.shift]||'Turno'} (${record.shift})`:'Não informado',getModelProfile(record.model||DEFAULT_MODEL).label,record.codeSerial||'—',record.printSerial||(record.originalOCR?'Texto incerto · ver detalhes':'Não lida')];for(const [index,value] of values.entries()){const td=document.createElement('td');td.dataset.label=['Data / hora','Inspetor','Turno','Modelo','Código 2D','Tampografia'][index];td.textContent=value;tr.append(td);}const status=document.createElement('td');status.dataset.label='Resultado';status.append(badge(record.status));tr.append(status);const sync=document.createElement('td');sync.dataset.label='Sincronização';sync.textContent=record.syncState==='pending'?'Neste aparelho · aguardando envio':record.syncState==='synced'?'Compartilhado':'Registro antigo local';tr.append(sync);const photoCell=document.createElement('td');photoCell.dataset.label='Foto';if(record.photoPresent){const photoButton=document.createElement('button');photoButton.className='text-button';photoButton.textContent='Ver foto';photoButton.onclick=()=>showPhoto(record);photoCell.append(photoButton);}else photoCell.textContent='Sem foto';tr.append(photoCell);const td=document.createElement('td');td.dataset.label='Registro';const button=document.createElement('button');button.className='text-button';button.textContent='Ver detalhes';button.onclick=()=>showDetails(record);td.append(button);tr.append(td);body.append(tr);}}
function showDetails(record){
  const model=record.model||DEFAULT_MODEL,profile=getModelProfile(model),parsed=compare(record.qr||'',record.ocr||'',model);
  const code=record.codeSerial||parsed.code.serial,print=record.printSerial||parsed.print.serial;
  const summary=document.createElement('div');summary.className='detail-summary';summary.append(badge(record.status));
  const date=document.createElement('span');date.textContent=new Date(record.date).toLocaleString('pt-BR');summary.append(date);
  const dl=document.createElement('dl');dl.className='detail-grid';
  for(const [label,value] of [['Inspetor',record.inspector||'Não informado'],['Turno',record.shift?`${SHIFT_LABELS[record.shift]||'Turno'} (${record.shift})`:'Não informado'],['Modelo',profile.label],['SEC CODE',record.qr?.split('+')[0]||'Não identificado'],['Série no código 2D',code||'Não identificada'],['Série na tampografia',print||'Não identificada'],['Conferência da impressão',record.visualDecision==='defect'?'Falha visual identificada':record.visualDecision==='clear'?'Sem falha visual identificada':'Não informada'],['Sincronização',record.syncState==='synced'?'Compartilhado':record.syncState==='pending'?'Aguardando envio':'Somente neste aparelho']]){const item=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;item.append(dt,dd);dl.append(item);}
  const table=document.createElement('section');table.className='position-details detail-positions';
  const heading=document.createElement('h3');heading.textContent='Validação por posição · '+profile.secCode;table.append(heading);
  const explanation=document.createElement('p');explanation.textContent='Texto fixo, data de fabricação, turno/linha e contador conforme a planilha. Vermelho indica diferença ou caractere fora do padrão.';table.append(explanation);
  if(code?.length===14&&print?.length===14){const head=document.createElement('div');head.className='position-head';for(const text of ['Pos.','Significado','QR','Foto']){const cell=document.createElement('span');cell.textContent=text;head.append(cell);}table.append(head,positionRows(comparePositions(code,print,model)));}
  else{const missing=document.createElement('p');missing.textContent='A tabela estará completa quando as duas séries de 14 caracteres forem identificadas.';table.append(missing);}
  const body=[summary,table,dl];
  if(record.reason&&record.status!=='COINCIDE'){const reason=document.createElement('p');reason.className='detail-reason';reason.textContent=record.reason;body.push(reason);}
  if(record.photoPresent){const photoButton=document.createElement('button');photoButton.type='button';photoButton.textContent='Abrir foto e ampliar';photoButton.onclick=()=>{$('#details').close();showPhoto(record);};body.push(photoButton);}
  $('#detail-body').replaceChildren(...body);$('#details').showModal();
}
$('#close-details').onclick=()=>$('#details').close();$('#more').onclick=()=>{limit+=50;renderHistory();};
async function showPhoto(record){
  if(photoUrl){URL.revokeObjectURL(photoUrl);photoUrl=null;}
  const image=$('#record-photo'),hint=$('#photo-hint');image.hidden=true;image.removeAttribute('src');resetPhotoZoom();
  hint.textContent=(record.syncState==='pending'?'Foto salva neste aparelho · aguardando envio. ':'Foto compartilhada do registro. ')+'Use dois dedos para ampliar e um dedo para mover a foto.';
  $('#photo-dialog').showModal();
  if(record.syncState==='pending'){
    const blob=await getPhoto(record.id).catch(()=>null);
    if(!blob){hint.textContent='Foto local indisponível. Confira a sincronização.';return;}
    photoUrl=URL.createObjectURL(blob);image.src=photoUrl;
  }else image.src=new URL('api/photos/'+encodeURIComponent(record.id),base).href;
  image.hidden=false;
  image.onload=()=>resetPhotoZoom();
  image.onerror=()=>{image.hidden=true;hint.textContent='A foto ainda não está disponível. Aguarde um instante e abra novamente.';};
}
$('#close-photo').onclick=()=>$('#photo-dialog').close();
let photoZoom=1,photoBaseWidth=0,pinchDistance=0,pinchZoom=1,dragTouch=null;
function fittedPhotoWidth(){const viewport=$('.photo-scroll'),image=$('#record-photo');if(!image.naturalWidth||!image.naturalHeight)return viewport.clientWidth;return Math.min(viewport.clientWidth,viewport.clientHeight*image.naturalWidth/image.naturalHeight);}
function setPhotoZoom(scale,anchorX,anchorY){const viewport=$('.photo-scroll'),x=anchorX??viewport.clientWidth/2,y=anchorY??viewport.clientHeight/2,oldWidth=Math.max(1,viewport.scrollWidth),oldHeight=Math.max(1,viewport.scrollHeight),relativeX=(viewport.scrollLeft+x)/oldWidth,relativeY=(viewport.scrollTop+y)/oldHeight;photoZoom=Math.max(1,Math.min(5,scale));$('#record-photo').style.width=Math.round(photoBaseWidth*photoZoom)+'px';viewport.scrollLeft=relativeX*viewport.scrollWidth-x;viewport.scrollTop=relativeY*viewport.scrollHeight-y;}
function resetPhotoZoom(){photoZoom=1;photoBaseWidth=fittedPhotoWidth();$('#record-photo').style.width=Math.round(photoBaseWidth)+'px';$('.photo-scroll').scrollTo(0,0);}
const photoViewport=$('.photo-scroll');
const distance=touches=>Math.hypot(touches[0].clientX-touches[1].clientX,touches[0].clientY-touches[1].clientY);
photoViewport.addEventListener('touchstart',event=>{if(event.touches.length===2){pinchDistance=distance(event.touches);pinchZoom=photoZoom;dragTouch=null;event.preventDefault();}else if(event.touches.length===1)dragTouch={x:event.touches[0].clientX,y:event.touches[0].clientY};},{passive:false});
photoViewport.addEventListener('touchmove',event=>{if(event.touches.length===2){event.preventDefault();if(!pinchDistance){pinchDistance=distance(event.touches);pinchZoom=photoZoom;}const box=photoViewport.getBoundingClientRect(),x=(event.touches[0].clientX+event.touches[1].clientX)/2-box.left,y=(event.touches[0].clientY+event.touches[1].clientY)/2-box.top;setPhotoZoom(pinchZoom*distance(event.touches)/Math.max(1,pinchDistance),x,y);}else if(event.touches.length===1&&dragTouch){event.preventDefault();const touch=event.touches[0];photoViewport.scrollLeft-=touch.clientX-dragTouch.x;photoViewport.scrollTop-=touch.clientY-dragTouch.y;dragTouch={x:touch.clientX,y:touch.clientY};}},{passive:false});
photoViewport.addEventListener('touchend',event=>{pinchDistance=0;dragTouch=event.touches.length===1?{x:event.touches[0].clientX,y:event.touches[0].clientY}:null;});
photoViewport.addEventListener('touchcancel',()=>{pinchDistance=0;dragTouch=null;});
$('#visual-open-photo').onclick=async()=>{if(!photoBase)return;if(photoUrl){URL.revokeObjectURL(photoUrl);photoUrl=null;}const blob=await jpeg(.9);if(!blob)return;photoUrl=URL.createObjectURL(blob);const image=$('#record-photo');image.onload=()=>resetPhotoZoom();image.src=photoUrl;image.hidden=false;$('#photo-hint').textContent='Use dois dedos para ampliar e um dedo para mover. Confira toda a tampografia antes de decidir.';$('#photo-dialog').showModal();};
window.addEventListener('resize',()=>{if($('#photo-dialog').open)resetPhotoZoom();});
$('#photo-dialog').addEventListener('close',()=>{if(photoUrl){URL.revokeObjectURL(photoUrl);photoUrl=null;}$('#record-photo').removeAttribute('src');});
function jpeg(quality){return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));}
async function archivePhoto(){
  ctx.putImageData(photoBase,0,0);
  for(const quality of [.78,.68,.55]){const blob=await jpeg(quality);if(blob&&blob.size<=2000000)return blob;}
  throw new Error('A foto ficou acima de 2 MB. Tire outra foto com resolução menor.');
}
async function persistComparison(){
if(saving||saved||!storageReady||!inspector||!inspectorShift||!photoBase){if(!storageReady)$('#save-message').textContent='Histórico indisponível. Esta captura ainda não foi salva.';else if(!inspector||!inspectorShift)$('#save-message').textContent='Informe seu nome e turno acima para registrar esta peça.';else if(!photoBase)$('#save-message').textContent='Tire a foto da peça antes de registrar.';return;}
if(!$('#confirmed').checked||$('#save').disabled)return;
const result=update();
const record={id:crypto.randomUUID(),date:new Date().toISOString(),inspector,shift:inspectorShift,model:selectedModel,syncState:'pending',photoPresent:true,status:result.status,reason:result.reason,rawComparison:result.rawComparison,automatic:false,ocrReliable,ocrAttempts,codeSerial:result.code.serial,printSerial:result.print.serial,qr:$('#qr').value,ocr:$('#ocr').value,originalCode,originalOCR,codeSource,printSource,format,confidence,codeEdited:$('#qr').value!==originalCode,printEdited:$('#ocr').value!==originalOCR,confirmed:$('#confirmed').checked,visualAssessment,visualDecision:visualDecision||null,rule:RULE+' / '+getModelProfile(selectedModel).version+' / camera-nativa-foto'};
saving=true;update();
try{const photo=await archivePhoto();await saveRecordWithPhoto(record,photo);saved=true;$('#save-message').textContent='Registro e foto salvos neste aparelho. Aguardando sincronização.';records=await listRecords();renderHistory();await syncNow();if(!records.find(item=>item.id===record.id&&item.syncState==='synced'))$('#save-message').textContent='Registro e foto salvos neste aparelho. Aguardando sincronização.';else $('#save-message').textContent='Registro e foto compartilhados: '+record.status+'.';}
catch(error){$('#save-message').textContent='Não foi possível salvar a foto e o registro. '+error.message;}
finally{saving=false;update();}
}
$('#save').onclick=()=>persistComparison();
$('#export').onclick=()=>{const visible=records.filter(record=>record.syncState==='synced'||record.inspector===inspector);const blob=new Blob([csv(visible)],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`valida-laser-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function renderInspectorOptions(){const select=$('#inspector-input');select.replaceChildren(new Option('Selecione o inspetor',''));for(const entry of inspectors.filter(item=>item.active))select.add(new Option(entry.name,entry.id));const current=inspectors.find(item=>item.active&&item.name===inspector);select.value=current?.id||'';if(!current){inspector='';inspectorShift='';localStorage.removeItem('laser-inspector');localStorage.removeItem('laser-shift');}}
function showInspector(){renderInspectorOptions();$('#model-select').value=selectedModel;for(const choice of document.querySelectorAll('input[name="shift"]'))choice.checked=choice.value===inspectorShift;$('#inspector-hint').textContent=inspector&&inspectorShift?`Novos registros: ${inspector} · ${getModelProfile(selectedModel).label} · ${SHIFT_LABELS[inspectorShift]} (${inspectorShift}).`:inspectors.some(item=>item.active)?'Escolha um inspetor cadastrado e confirme o turno antes de registrar uma peça.':'Nenhum inspetor ativo. Cadastre um nome na aba Gestão de inspetores.';update();renderHistory();}
$('#model-select').onchange=()=>{const next=$('#model-select').value;if(!isModelCode(next)||next===selectedModel)return;selectedModel=next;localStorage.setItem('laser-model',selectedModel);photoBase=null;canvas.hidden=true;$('#camera-empty').hidden=false;$('#crop-tools').hidden=true;clearReadings();$('#inspector-hint').textContent=inspector&&inspectorShift?`Novos registros: ${inspector} · ${getModelProfile(selectedModel).label} · ${SHIFT_LABELS[inspectorShift]} (${inspectorShift}).`:'Informe seu nome e turno antes de registrar uma peça.';message(getModelProfile(selectedModel).label+' selecionado. Tire uma nova foto para este modelo.');};
async function syncNow(){if(syncBusy||!navigator.onLine)return;syncBusy=true;$('#sync-status').textContent='Sincronizando…';try{records=await syncRecords();renderHistory();const pending=records.filter(item=>item.syncState==='pending').length;$('#sync-status').textContent=pending?`${pending} registro(s) aguardando envio`:'Histórico compartilhado atualizado';}catch{$('#sync-status').textContent='Sem conexão com o servidor · registros locais preservados';}finally{syncBusy=false;}}
$('#inspector-input').onchange=()=>{const entry=inspectors.find(item=>item.active&&item.id===$('#inspector-input').value);for(const choice of document.querySelectorAll('input[name="shift"]'))choice.checked=choice.value===entry?.shift;};
$('#inspector-form').onsubmit=event=>{event.preventDefault();const entry=inspectors.find(item=>item.active&&item.id===$('#inspector-input').value),selectedShift=document.querySelector('input[name="shift"]:checked')?.value||'';if(!entry||!isShiftCode(selectedShift))return;inspector=entry.name;inspectorShift=selectedShift;localStorage.setItem('laser-inspector',inspector);localStorage.setItem('laser-shift',inspectorShift);showInspector();document.activeElement?.blur();};
function managementMessage(text,error=false){const node=$('#management-message');node.textContent=text;node.classList.toggle('error',error);}
function managerHeader(){return btoa(String.fromCharCode(...new TextEncoder().encode(managerPassword)));}
function lockManagement(message='Digite a senha de gestor para continuar.'){managerPassword='';$('#manager-content').hidden=true;$('#manager-lock').hidden=false;$('#manager-password').value='';$('#manager-auth-message').textContent=message;$('#manager-auth-message').classList.toggle('error',message.includes('incorreta')||message.includes('expirou'));}
function requireManagerResponse(response){if(response.status===401){lockManagement('Senha incorreta ou acesso expirou. Digite a senha novamente.');throw new Error('Acesso de gestor necessário.');}return response;}
$('#manager-unlock-form').onsubmit=async event=>{event.preventDefault();const password=$('#manager-password').value;$('#manager-auth-message').textContent='Verificando senha…';try{const response=await fetch(new URL('api/management/unlock',base),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível verificar a senha.');managerPassword=password;$('#manager-password').value='';$('#manager-auth-message').textContent='';$('#manager-lock').hidden=true;$('#manager-content').hidden=false;await loadInspectors();}catch(error){managerPassword='';$('#manager-auth-message').textContent=error.message;$('#manager-auth-message').classList.add('error');}};
function resetManagementForm(){$('#management-form').reset();$('#management-id').value='';$('#management-save').textContent='Cadastrar inspetor';$('#management-cancel').hidden=true;}
function renderManagement(){const body=$('#management-list');body.replaceChildren();$('#management-empty').hidden=inspectors.length>0;for(const entry of inspectors){const row=document.createElement('tr');for(const [label,value] of [['Nome',entry.name],['Turno padrão',`${SHIFT_LABELS[entry.shift]} (${entry.shift})`],['Situação',entry.active?'Ativo':'Inativo']]){const cell=document.createElement('td');cell.dataset.label=label;cell.textContent=value;row.append(cell);}const actions=document.createElement('td');actions.dataset.label='Ações';const edit=document.createElement('button');edit.type='button';edit.className='text-button';edit.textContent='Editar';edit.onclick=()=>{$('#management-id').value=entry.id;$('#management-name').value=entry.name;$('#management-shift').value=entry.shift;$('#management-save').textContent='Salvar alteração';$('#management-cancel').hidden=false;$('#management-name').focus();};const toggle=document.createElement('button');toggle.type='button';toggle.className='text-button';toggle.textContent=entry.active?'Desativar':'Reativar';toggle.onclick=async()=>{try{const response=requireManagerResponse(await fetch(new URL('api/inspectors/'+encodeURIComponent(entry.id),base),entry.active?{method:'DELETE',headers:{'X-Manager-Key':managerHeader()}}:{method:'POST',headers:{'Content-Type':'application/json','X-Manager-Key':managerHeader()},body:JSON.stringify({...entry,active:true})}));const result=await response.json();if(!response.ok)throw new Error(result.error||'Falha ao atualizar.');await loadInspectors();managementMessage(entry.active?'Inspetor desativado. O histórico permanece.':'Inspetor reativado.');}catch(error){if(managerPassword)managementMessage(error.message,true);}};actions.append(edit,toggle);row.append(actions);body.append(row);}for(const selector of ['#management-name','#management-shift','#management-save'])$(selector).disabled=!rosterOnline;}
async function loadInspectors(){try{const response=await fetch(new URL('api/inspectors',base),{cache:'no-store'});if(!response.ok)throw new Error('Cadastro indisponível.');const data=await response.json();inspectors=Array.isArray(data.inspectors)?data.inspectors:[];rosterOnline=true;localStorage.setItem('laser-inspectors',JSON.stringify(inspectors));managementMessage('Cadastro compartilhado atualizado.');}catch{rosterOnline=false;try{const cached=JSON.parse(localStorage.getItem('laser-inspectors')||'[]');inspectors=Array.isArray(cached)?cached:[];}catch{inspectors=[];}managementMessage('Sem conexão com o cadastro. A lista salva neste aparelho continua disponível; alterações exigem internet.',true);}showInspector();renderManagement();}
$('#management-form').onsubmit=async event=>{event.preventDefault();if(!rosterOnline||!managerPassword)return;const id=$('#management-id').value,name=normalizeInspectorName($('#management-name').value),shift=$('#management-shift').value;if(name.length<2||name.length>80||!isShiftCode(shift)){managementMessage('Informe nome e turno válidos.',true);return;}$('#management-save').disabled=true;try{const response=requireManagerResponse(await fetch(new URL('api/inspectors',base),{method:'POST',headers:{'Content-Type':'application/json','X-Manager-Key':managerHeader()},body:JSON.stringify({id:id||undefined,name,shift})}));const result=await response.json();if(!response.ok)throw new Error(result.error||'Falha ao salvar.');resetManagementForm();await loadInspectors();managementMessage(id?'Cadastro atualizado.':'Inspetor cadastrado.');}catch(error){if(managerPassword)managementMessage(error.message,true);}finally{$('#management-save').disabled=!rosterOnline;}};
$('#management-cancel').onclick=resetManagementForm;
$('#management-refresh').onclick=loadInspectors;
function showTab(name){const management=name==='management';$('#inspection-view').hidden=management;$('#management-view').hidden=!management;$('#tab-inspection').classList.toggle('active',!management);$('#tab-management').classList.toggle('active',management);$('#tab-inspection').setAttribute('aria-current',management?'false':'page');$('#tab-management').setAttribute('aria-current',management?'page':'false');if(management){$('#manager-lock').hidden=Boolean(managerPassword);$('#manager-content').hidden=!managerPassword;if(managerPassword)loadInspectors();else $('#manager-password').focus();}}
$('#tab-inspection').onclick=()=>showTab('inspection');$('#tab-management').onclick=()=>showTab('management');
$('#sync-button').onclick=syncNow;
window.addEventListener('online',syncNow);
setInterval(syncNow,30000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncNow();});
async function init(){try{records=await listRecords();storageReady=true;}catch{$('#storage-status').textContent='Armazenamento indisponível';$('#save-message').textContent='Este navegador não permitiu salvar o histórico. Use uma janela normal com armazenamento habilitado.';}inspector=localStorage.getItem('laser-inspector')||'';inspectorShift=localStorage.getItem('laser-shift')||'';selectedModel=localStorage.getItem('laser-model')||DEFAULT_MODEL;if(!isModelCode(selectedModel))selectedModel=DEFAULT_MODEL;if(!isShiftCode(inspectorShift))inspectorShift='';await loadInspectors();await syncNow();if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;$('#offline-state').textContent=navigator.onLine?'Leitura offline após primeira captura':'Modo offline';}catch{$('#offline-state').textContent='Offline indisponível';}}}
let installPrompt;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#install').hidden=false;});$('#install').onclick=async()=>{await installPrompt?.prompt();installPrompt=null;$('#install').hidden=true;};window.addEventListener('focus',checkNativeReturn);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkNativeReturn();});init();
try{document.modelContext?.registerTool({name:'read_comparison_summary',description:'Lê a comparação atual e a quantidade de registros locais. Não salva nem altera dados.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||Object.keys(input).length)throw new Error('Não são aceitos parâmetros.');return {comparison:inspect($('#qr').value,$('#ocr').value,ocrReliable,$('#confirmed').checked,inspectorShift,selectedModel),recordCount:records.length};}});}catch{}
