import {readBarcodes,prepareZXingModule} from 'zxing-wasm/reader';
import {createWorker} from 'tesseract.js';
import {compare,csv,RULE,extractPrint} from './compare.mjs';
import {selectOCR,inspect,nearbyRegion} from './inspection.mjs';
import {readPrintedSerial} from './paddle-reader.mjs';
import {saveRecord,listRecords} from './storage.mjs';
import {syncRecords} from './sync.mjs';
import {enableContinuousFocus,refocusCamera,captureSharpestFrame} from './camera-focus.mjs';
import {usesProfile,SHIFT_LABELS,isShiftCode} from './serial-profile.mjs';
const $=s=>document.querySelector(s);const base=new URL('./',location.href);const asset=p=>new URL(p,base).href;
prepareZXingModule({overrides:{locateFile:path=>path.endsWith('.wasm')?asset('vendor/zxing_reader.wasm'):path}});
let stream=null,worker=null,busy=false,saving=false,saved=false,records=[],limit=50,originalCode='',originalOCR='',codeSource='manual',printSource='manual',format='',confidence=null,photoBase=null,cropMode=false,crop=null,start=null,storageReady=false,ocrReliable=false,ocrAttempts=[],codePosition=null,captureSource='foto',inspector='',inspectorShift='',syncBusy=false,nativeCapturePending=false,processingUpload=false,nativeReturnTimer=null;
const canvas=$('#photo'),ctx=canvas.getContext('2d',{willReadFrequently:true});
function message(text,error=false){for(const selector of ['#scan-message','#capture-feedback']){const node=$(selector);node.textContent=text;node.classList.toggle('error',error);}}
function setBusy(value){busy=value;for(const s of ['#camera','#capture','#refocus','#native-trigger','#native-file','#file','#new','#crop-start','#crop-read','#detail-read','#invert','#inspector-input','#shift-input','#inspector-submit'])$(s).disabled=value;$('#qr').disabled=value;$('#ocr').disabled=value;$('#confirmed').disabled=value;$('#progress').hidden=!value;update();}
function renderPositions(profile){const panel=$('#position-details'),list=$('#position-list');panel.hidden=!profile;if(!profile){list.replaceChildren();return;}const fragment=document.createDocumentFragment();for(const item of profile.positions){const row=document.createElement('div');row.className='position-row '+(!item.valid||!item.printValid||!item.match?'position-error':'position-match');const number=document.createElement('span'),meaning=document.createElement('span'),code=document.createElement('strong'),print=document.createElement('strong');number.textContent=String(item.position);meaning.textContent=item.meaning+(item.expected?' · esperado '+item.expected:item.position===7?' · G=1ª H=2ª J=3ª':'');code.textContent=item.code;print.textContent=item.print;row.append(number,meaning,code,print);fragment.append(row);}list.replaceChildren(fragment);}
function canReviewI(result){return !!result.ambiguousI;}
function update(){const inspection=inspect($('#qr').value,$('#ocr').value,ocrReliable,$('#confirmed').checked,inspectorShift);const result=!inspectorShift&&inspection.status==='COINCIDE'?{...inspection,status:'PENDENTE',reason:'Selecione seu turno para validar o código 2D.'}:inspection;$('#qr-series').textContent=result.code.serial||'Não identificado';$('#print-series').textContent=result.print.serial||'Não identificado';renderPositions(result.profile);const shiftStatus=$('#shift-check');shiftStatus.className='shift-check '+({match:'match',mismatch:'mismatch'}[result.shiftCheck.status]||'pending');shiftStatus.textContent=!inspectorShift?'Selecione seu turno acima para validar a letra do código 2D.':result.shiftCheck.status==='unread'?`${SHIFT_LABELS[inspectorShift]} (${inspectorShift}) selecionado. Leia o código 2D para conferir o turno.`:result.shiftCheck.status==='match'?`Código 2D correto para ${SHIFT_LABELS[inspectorShift]}: posição 7 = ${inspectorShift}.`:result.shiftCheck.status==='mismatch'?`Código 2D incorreto para ${SHIFT_LABELS[inspectorShift]}: esperado ${inspectorShift}, lido ${result.shiftCheck.actual} na posição 7.`:'Este formato de código 2D não permite validar o turno.';$('#confirmed-label').textContent=result.status==='PENDENTE'&&result.rawComparison==='COINCIDE'?'Conferi a peça: os 14 caracteres são iguais.':result.status==='PENDENTE'&&result.rawComparison==='DIVERGENTE'?'Conferi a peça e confirmo a diferença.':'Conferência manual: revisei a leitura com a peça.';const reviewI=canReviewI(result);$('#i-review').hidden=!reviewI;$('#i-correct').disabled=!reviewI||!$('#confirmed').checked||busy;const style={COINCIDE:'match',DIVERGENTE:'mismatch',PENDENTE:'pending'}[result.status];$('#result').className='result '+style;$('#result .result-symbol').textContent={COINCIDE:'✓',DIVERGENTE:'≠',PENDENTE:'!'}[result.status];$('#result strong').textContent={COINCIDE:'Os 14 caracteres coincidem',DIVERGENTE:'Série ou turno do código 2D divergente',PENDENTE:!inspectorShift?'Turno não informado':result.rawComparison==='COINCIDE'?'Séries coincidem · confira OCR':'Leitura pendente'}[result.status];$('#result p').textContent=result.status==='PENDENTE'?result.reason:result.status==='DIVERGENTE'?result.reason||'Os valores após + e : são diferentes. Confira a peça antes de registrar.':'Os 14 caracteres após + e : coincidem; a letra do código 2D corresponde ao turno selecionado.';const hasData=!!($('#qr').value.trim()||$('#ocr').value.trim());$('#save').disabled=busy||saving||saved||!storageReady||!inspector||!inspectorShift||!hasData;$('#save').textContent=saved?'Comparação registrada':result.status==='PENDENTE'?'Registrar leitura pendente':'Registrar comparação';return result;}
for(const id of ['#qr','#ocr'])$(id).addEventListener('input',()=>{$('#confirmed').checked=false;saved=false;ocrReliable=false;$('#save-message').textContent='';update();});$('#confirmed').addEventListener('change',()=>{saved=false;update();});
$('#i-correct').onclick=()=>{const result=inspect($('#qr').value,$('#ocr').value,ocrReliable,$('#confirmed').checked,inspectorShift);if(!$('#confirmed').checked||!canReviewI(result))return;const text=$('#ocr').value,serial=result.print.serial,index=text.indexOf(serial);if(index<0||text.indexOf(serial,index+1)>=0)return;const corrected=serial.slice(0,11)+'I'+serial.slice(12);$('#ocr').value=text.slice(0,index)+corrected+text.slice(index+serial.length);ocrReliable=false;saved=false;$('#save-message').textContent='Correção manual do OCR aplicada. O texto original continua guardado no registro.';update();};
function stopCamera(){stream?.getTracks().forEach(t=>t.stop());stream=null;$('#video').srcObject=null;$('#video').hidden=true;$('#capture').hidden=true;$('#refocus').hidden=true;$('#stop').hidden=true;$('#camera').hidden=false;if(!photoBase)$('#camera-empty').hidden=false;}
$('#stop').onclick=stopCamera;
$('#camera').onclick=async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('A câmera precisa de HTTPS ou localhost. Use Escolher foto neste aparelho.');stopCamera();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:3840},height:{ideal:2160}},audio:false});const track=stream.getVideoTracks()[0];const continuous=await enableContinuousFocus(track);const video=$('#video');video.srcObject=stream;await video.play();video.hidden=false;canvas.hidden=true;$('#camera-empty').hidden=true;$('#capture').hidden=false;$('#refocus').hidden=false;$('#stop').hidden=false;$('#camera').hidden=true;$('#crop-tools').hidden=true;message(continuous?'Foco contínuo solicitado. Afaste o celular até as letras ficarem nítidas; toque na série para refocar.':'Afaste o celular até as letras ficarem nítidas. Se continuar borrado, use a câmera do celular.');}catch(error){stopCamera();message(error.name==='NotAllowedError'?'Câmera não autorizada. Permita o acesso no navegador ou escolha uma foto.':error.message,true);}};
async function requestFocus(point){const track=stream?.getVideoTracks()[0];if(!track)return;message('Ajustando foco…');const applied=await refocusCamera(track,point);message(applied?'Foco solicitado. Se as letras ainda estiverem borradas, afaste o celular.':'O navegador não oferece controle de foco nesta câmera. Afaste o celular ou use a câmera do celular.',!applied);}
$('#refocus').onclick=()=>requestFocus({x:.5,y:.5});
$('#video').onpointerup=event=>{if(!stream)return;const video=$('#video'),rect=video.getBoundingClientRect(),scale=Math.min(rect.width/video.videoWidth,rect.height/video.videoHeight),shownWidth=video.videoWidth*scale,shownHeight=video.videoHeight*scale,left=rect.left+(rect.width-shownWidth)/2,top=rect.top+(rect.height-shownHeight)/2;const x=Math.max(0,Math.min(1,(event.clientX-left)/shownWidth)),y=Math.max(0,Math.min(1,(event.clientY-top)/shownHeight));requestFocus({x,y});};
function clearReadings(){ocrReliable=false;ocrAttempts=[];codePosition=null;originalCode='';originalOCR='';codeSource='manual';printSource='manual';format='';confidence=null;saved=false;$('#qr').value='';$('#ocr').value='';$('#confirmed').checked=false;$('#code-format').textContent='Aguardando leitura';$('#confidence').textContent='Leitura OCR';$('#save-message').textContent='';update();}
function setPhoto(image,width,height){const scale=Math.min(1,2560/Math.max(width,height));canvas.width=Math.round(width*scale);canvas.height=Math.round(height*scale);ctx.drawImage(image,0,0,canvas.width,canvas.height);photoBase=ctx.getImageData(0,0,canvas.width,canvas.height);canvas.hidden=false;$('#camera-empty').hidden=true;$('#crop-tools').hidden=false;crop=null;cropMode=false;canvas.classList.remove('selecting');$('#crop-read').disabled=true;}
$('#capture').onclick=async()=>{const video=$('#video');if(!video.videoWidth){message('Aguarde a imagem da câmera.',true);return;}$('#capture').disabled=true;try{message('Refocando e escolhendo o quadro mais nítido…');await refocusCamera(stream.getVideoTracks()[0]);const frame=await captureSharpestFrame(video).catch(()=>null);clearReadings();captureSource='câmera';if(frame){setPhoto(frame,frame.width,frame.height);frame.close();}else setPhoto(video,video.videoWidth,video.videoHeight);stopCamera();await readPhoto(false);}catch(error){message('Não foi possível capturar a imagem. '+error.message,true);$('#capture').disabled=false;}};
async function loadPhoto(event){if(processingUpload)return;const file=event.target.files?.[0];if(!file){if(event.target.id==='native-file'){nativeCapturePending=false;message('Nenhuma foto voltou da câmera. Se ela salvou a imagem, toque em Escolher foto para selecioná-la.',true);}return;}processingUpload=true;nativeCapturePending=false;clearTimeout(nativeReturnTimer);message('Foto recebida. Abrindo imagem…');stopCamera();clearReadings();captureSource=event.target.id==='native-file'?'câmera do celular':'foto';photoBase=null;canvas.hidden=true;$('#camera-empty').hidden=false;$('#crop-tools').hidden=true;let image=null,url=null;try{try{image=await createImageBitmap(file);}catch{url=URL.createObjectURL(file);image=new Image();image.src=url;await image.decode();}setPhoto(image,image.width,image.height);image?.close?.();image=null;if(url){URL.revokeObjectURL(url);url=null;}message('Foto carregada. Iniciando leitura…');await readPhoto(false);}catch(error){message('Não foi possível abrir ou ler esta foto. Se ela foi salva, tente Escolher foto. '+error.message,true);}finally{image?.close?.();if(url)URL.revokeObjectURL(url);event.target.value='';processingUpload=false;}}
function checkNativeReturn(){if(!nativeCapturePending||document.hidden)return;clearTimeout(nativeReturnTimer);nativeReturnTimer=setTimeout(()=>{if(!nativeCapturePending||document.hidden)return;const input=$('#native-file');if(input.files?.length)loadPhoto({target:input});else{nativeCapturePending=false;message('A câmera não entregou a foto ao aplicativo. Se a imagem foi salva, toque em Escolher foto e selecione-a.',true);}},2500);}
$('#native-trigger').onclick=()=>{nativeCapturePending=true;message('Abrindo a câmera do celular. Depois da foto, aguarde o retorno ao aplicativo…');$('#native-file').click();setTimeout(checkNativeReturn,500);};
$('#file').onchange=loadPhoto;$('#native-file').onchange=loadPhoto;$('#native-file').oninput=loadPhoto;
async function ocrWorker(){if(!worker){worker=await createWorker('eng',1,{workerPath:asset('vendor/worker.min.js'),corePath:asset('vendor/'),langPath:asset('vendor/'),logger:info=>{if(info.status==='recognizing text')$('#progress').value=info.progress;}});}return worker;}
function preprocessOCR(context,width,height,invert){const image=context.getImageData(0,0,width,height),data=image.data,hist=new Uint32Array(256);for(let i=0;i<data.length;i+=4){const g=Math.round(.299*data[i]+.587*data[i+1]+.114*data[i+2]);data[i]=g;hist[g]++;}const cutoff=width*height*.02;let low=0,high=255,sum=0;while(low<254&&(sum+=hist[low])<cutoff)low++;sum=0;while(high>low&&(sum+=hist[high])<cutoff)high--;for(let i=0;i<data.length;i+=4){let v=Math.max(0,Math.min(255,(data[i]-low)*255/Math.max(1,high-low)));if(invert)v=255-v;data[i]=data[i+1]=data[i+2]=v;}context.putImageData(image,0,0);}
async function readPhoto(selectionOnly,detailed=false){if(busy||!photoBase)return;setBusy(true);saved=false;$('#confirmed').checked=false;$('#save-message').textContent='';ctx.putImageData(photoBase,0,0);const problems=[];try{
if(!selectionOnly){$('#qr').value='';originalCode='';format='';codeSource=captureSource;$('#code-format').textContent='Procurando código';message('Lendo QR Code / Data Matrix…');try{const codes=(await readBarcodes(photoBase,{formats:['QRCode','DataMatrix'],tryHarder:true,tryInvert:true,maxNumberOfSymbols:8})).filter(c=>c.isValid!==false);if(codes.length===1){originalCode=codes[0].text;$('#qr').value=originalCode;format=codes[0].format;codePosition=codes[0].position;$('#code-format').textContent=format;}else{problems.push(codes.length?'Mais de um código na foto. Fotografe uma peça por vez.':'Código não encontrado. Aproxime a câmera ou use um leitor USB.');$('#code-format').textContent='Não identificado';}}catch{problems.push('Falha ao iniciar o leitor de código. Tente reabrir o aplicativo com internet.');}}
$('#ocr').value='';originalOCR='';confidence=null;ocrReliable=false;ocrAttempts=[];printSource=(detailed?'OCR detalhado':'OCR rápido')+' · '+captureSource;$('#confidence').textContent='Lendo…';message('Localizando e reconhecendo a linha da série…');
try{
  const region=selectionOnly&&crop?crop:nearbyRegion(codePosition,canvas.width,canvas.height);
  ocrAttempts=await readPrintedSerial(canvas,region,text=>message(text),$('#invert').checked,detailed);
  const best=selectOCR(ocrAttempts,usesProfile($('#qr').value));originalOCR=best.text;confidence=best.confidence;ocrReliable=best.reliable;
  $('#ocr').value=originalOCR;const bestSerial=extractPrint(originalOCR).serial,agreements=bestSerial?ocrAttempts.filter(attempt=>extractPrint(attempt.text).serial===bestSerial).length:0;$('#confidence').textContent='OCR · '+agreements+'/'+ocrAttempts.length+' leituras da mesma série · score '+confidence+'/100'+(ocrReliable?'':' · revisar');
  if(!ocrReliable)problems.push(compare($('#qr').value,$('#ocr').value).status==='COINCIDE'?'As séries exibidas coincidem. O OCR não confirmou a série com confiança em todas as tentativas. Confira a peça e marque a conferência manual para concluir.':'O OCR não confirmou a série com confiança. Confira a peça ou selecione a linha da série para ler novamente.');
}catch{worker?.terminate();worker=null;$('#confidence').textContent='OCR indisponível';problems.push('Falha no reconhecimento da tampografia. A tentativa será registrada como pendente.');}
message(problems.length?problems.join(' '):inspectorShift?'As duas leituras foram comparadas automaticamente.':'Séries lidas. Selecione seu turno para validar o código 2D.',problems.length>0&&compare($('#qr').value,$('#ocr').value).status!=='COINCIDE');
}finally{setBusy(false);crop=null;$('#crop-read').disabled=true;update();}
await persistComparison(true);
}
$('#crop-read').onclick=()=>readPhoto(true,true);$('#detail-read').onclick=()=>readPhoto(true,true);
$('#crop-start').onclick=()=>{cropMode=true;crop=null;canvas.classList.add('selecting');ctx.putImageData(photoBase,0,0);$('#crop-read').disabled=true;message('Arraste sobre a linha inteira, incluindo NÚMERO DE SÉRIE e todos os caracteres.');};
function point(event){const r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(event.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height,(event.clientY-r.top)*canvas.height/r.height))};}
canvas.onpointerdown=e=>{if(!cropMode||busy)return;start=point(e);canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!start)return;const p=point(e);crop={x:Math.round(Math.min(start.x,p.x)),y:Math.round(Math.min(start.y,p.y)),w:Math.round(Math.abs(p.x-start.x)),h:Math.round(Math.abs(p.y-start.y))};ctx.putImageData(photoBase,0,0);ctx.strokeStyle='#28f4c0';ctx.lineWidth=Math.max(2,canvas.width/350);ctx.strokeRect(crop.x,crop.y,crop.w,crop.h);};canvas.onpointerup=()=>{if(!start)return;start=null;cropMode=false;canvas.classList.remove('selecting');$('#crop-read').disabled=!crop||crop.w<30||crop.h<8;};canvas.onpointercancel=()=>{start=null;crop=null;cropMode=false;canvas.classList.remove('selecting');ctx.putImageData(photoBase,0,0);};
$('#new').onclick=()=>{stopCamera();clearReadings();photoBase=null;canvas.hidden=true;$('#camera-empty').hidden=false;$('#crop-tools').hidden=true;message('Pronto para a próxima peça.');$('#qr').focus();};
function badge(status){const b=document.createElement('span');b.className='badge '+{COINCIDE:'match',DIVERGENTE:'mismatch',PENDENTE:'pending'}[status];b.textContent=status;return b;}
function renderHistory(){const visible=records.filter(record=>record.syncState==='synced'||record.inspector===inspector);$('#count').textContent=visible.length;$('#empty-history').hidden=visible.length>0;$('#export').disabled=!visible.length;$('#more').hidden=visible.length<=limit;const body=$('#history');body.replaceChildren();for(const record of visible.slice(0,limit)){const tr=document.createElement('tr');const values=[new Date(record.date).toLocaleString('pt-BR'),record.inspector||'Registro antigo',record.shift?`${SHIFT_LABELS[record.shift]||'Turno'} (${record.shift})`:'Não informado',record.codeSerial||'—',record.printSerial||(record.originalOCR?'Texto incerto · ver detalhes':'Não lida')];for(const [index,value] of values.entries()){const td=document.createElement('td');td.dataset.label=['Data / hora','Inspetor','Turno','Código 2D','Tampografia'][index];td.textContent=value;tr.append(td);}const status=document.createElement('td');status.dataset.label='Resultado';status.append(badge(record.status));tr.append(status);const sync=document.createElement('td');sync.dataset.label='Sincronização';sync.textContent=record.syncState==='pending'?'Neste aparelho · aguardando envio':record.syncState==='synced'?'Compartilhado':'Registro antigo local';tr.append(sync);const td=document.createElement('td');td.dataset.label='Registro';const button=document.createElement('button');button.className='text-button';button.textContent='Ver detalhes';button.onclick=()=>showDetails(record);td.append(button);tr.append(td);body.append(tr);}}
function showDetails(record){const dl=document.createElement('dl');const fields={'Registro':record.id,'Inspetor':record.inspector||'Registro antigo','Turno informado':record.shift?`${SHIFT_LABELS[record.shift]||'Turno'} (${record.shift})`:'Não informado','Turno no código 2D':record.codeSerial?.[6]||'Não identificado','Sincronização':record.syncState==='pending'?'Aguardando envio':record.syncState==='synced'?'Compartilhado':'Somente neste aparelho','Data / hora':new Date(record.date).toLocaleString('pt-BR'),'Resultado':record.status,'Motivo da pendência':record.reason||'—','Registro automático':record.automatic?'Sim':'Não','Passagens do OCR':record.ocrAttempts?.map((a,i)=>'Leitura '+(i+1)+' · '+(a.model||'Tesseract')+' · '+(a.variant||a.mode||'')+' ('+a.confidence+'%): '+a.text).join('\n\n')||'Não disponíveis','Série no código':record.codeSerial||'Não identificada','Série na tampografia':record.printSerial||'Não identificada','Código original':record.originalCode||'(entrada manual)','Código utilizado':record.qr,'Texto OCR original':record.originalOCR||'(sem OCR)','Texto da tampografia utilizado':record.ocr,'Formato':record.format||'Manual','Confiança OCR':record.confidence===null?'Não disponível':record.confidence+'%','Origem':`${record.codeSource} / ${record.printSource}`,'Correções manuais':`Código: ${record.codeEdited?'sim':'não'} · Tampografia: ${record.printEdited?'sim':'não'}`,'Conferência visual':record.confirmed?'Confirmada pelo operador':'Não confirmada','Regra':record.rule};for(const [key,value]of Object.entries(fields)){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;dl.append(dt,dd);}$('#detail-body').replaceChildren(dl);$('#details').showModal();}
$('#close-details').onclick=()=>$('#details').close();$('#more').onclick=()=>{limit+=50;renderHistory();};
async function persistComparison(automatic=false){
if(saving||saved||!storageReady||!inspector||!inspectorShift){if(!storageReady)$('#save-message').textContent='Histórico indisponível. Esta captura ainda não foi salva.';else if(!inspector||!inspectorShift)$('#save-message').textContent='Informe seu nome e turno acima para registrar esta peça.';return;}
if(!automatic&&$('#save').disabled)return;
const result=update();
const record={id:crypto.randomUUID(),date:new Date().toISOString(),inspector,shift:inspectorShift,syncState:'pending',status:result.status,reason:result.reason,rawComparison:result.rawComparison,automatic,ocrReliable,ocrAttempts,codeSerial:result.code.serial,printSerial:result.print.serial,qr:$('#qr').value,ocr:$('#ocr').value,originalCode,originalOCR,codeSource,printSource,format,confidence,codeEdited:$('#qr').value!==originalCode,printEdited:$('#ocr').value!==originalOCR,confirmed:$('#confirmed').checked,rule:RULE+' / camera-v3-paddle'};
saving=true;update();
try{await saveRecord(record);saved=true;$('#save-message').textContent='Salvo neste aparelho. Aguardando sincronização.';records=await listRecords();renderHistory();await syncNow();if(!records.find(item=>item.id===record.id&&item.syncState==='synced'))$('#save-message').textContent='Salvo neste aparelho. Aguardando sincronização.';else $('#save-message').textContent=(automatic?'Captura registrada automaticamente: ':'Registro compartilhado: ')+record.status+'.';}
catch{$('#save-message').textContent='Não foi possível confirmar o salvamento. Confira o histórico antes de tentar novamente.';}
finally{saving=false;update();}
}
$('#save').onclick=()=>persistComparison(false);
$('#export').onclick=()=>{const visible=records.filter(record=>record.syncState==='synced'||record.inspector===inspector);const blob=new Blob([csv(visible)],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`valida-laser-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function showInspector(){$('#inspector-input').value=inspector;$('#shift-input').value=inspectorShift;$('#inspector-hint').textContent=inspector&&inspectorShift?`Novos registros: ${inspector} · ${SHIFT_LABELS[inspectorShift]} (${inspectorShift}).`:'Informe seu nome e turno antes de registrar uma peça.';update();renderHistory();}
async function syncNow(){if(syncBusy||!navigator.onLine)return;syncBusy=true;$('#sync-status').textContent='Sincronizando…';try{records=await syncRecords();renderHistory();const pending=records.filter(item=>item.syncState==='pending').length;$('#sync-status').textContent=pending?`${pending} registro(s) aguardando envio`:'Histórico compartilhado atualizado';}catch{$('#sync-status').textContent='Sem conexão com o servidor · registros locais preservados';}finally{syncBusy=false;}}
$('#inspector-form').onsubmit=event=>{event.preventDefault();const name=$('#inspector-input').value.trim().replace(/\s+/g,' '),selectedShift=$('#shift-input').value;if(!name||!isShiftCode(selectedShift))return;inspector=name;inspectorShift=selectedShift;localStorage.setItem('laser-inspector',inspector);localStorage.setItem('laser-shift',inspectorShift);showInspector();$('#shift-input').blur();};
$('#sync-button').onclick=syncNow;
window.addEventListener('online',syncNow);
setInterval(syncNow,30000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncNow();});
async function init(){try{records=await listRecords();storageReady=true;}catch{$('#storage-status').textContent='Armazenamento indisponível';$('#save-message').textContent='Este navegador não permitiu salvar o histórico. Use uma janela normal com armazenamento habilitado.';}inspector=localStorage.getItem('laser-inspector')||'';inspectorShift=localStorage.getItem('laser-shift')||'';if(!isShiftCode(inspectorShift))inspectorShift='';showInspector();await syncNow();if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;$('#offline-state').textContent=navigator.onLine?'Leitura offline após primeira captura':'Modo offline';}catch{$('#offline-state').textContent='Offline indisponível';}}}
let installPrompt;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#install').hidden=false;});$('#install').onclick=async()=>{await installPrompt?.prompt();installPrompt=null;$('#install').hidden=true;};window.addEventListener('pagehide',stopCamera);window.addEventListener('focus',checkNativeReturn);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();else checkNativeReturn();});init();
try{document.modelContext?.registerTool({name:'read_comparison_summary',description:'Lê a comparação atual e a quantidade de registros locais. Não salva nem altera dados.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||Object.keys(input).length)throw new Error('Não são aceitos parâmetros.');return {comparison:inspect($('#qr').value,$('#ocr').value,ocrReliable,$('#confirmed').checked,inspectorShift),recordCount:records.length};}});}catch{}
