import {readBarcodes,prepareZXingModule} from 'zxing-wasm/reader';
import {createWorker} from 'tesseract.js';
import {compare,csv,RULE,extractPrint} from './compare.mjs';
import {selectOCR,inspect,nearbyRegion} from './inspection.mjs';
import {readPrintedSerial} from './paddle-reader.mjs';
import {saveRecord,listRecords} from './storage.mjs';
const $=s=>document.querySelector(s);const base=new URL('./',location.href);const asset=p=>new URL(p,base).href;
prepareZXingModule({overrides:{locateFile:path=>path.endsWith('.wasm')?asset('vendor/zxing_reader.wasm'):path}});
let stream=null,worker=null,busy=false,saving=false,saved=false,records=[],limit=50,originalCode='',originalOCR='',codeSource='manual',printSource='manual',format='',confidence=null,photoBase=null,cropMode=false,crop=null,start=null,storageReady=false,ocrReliable=false,ocrAttempts=[],codePosition=null,captureSource='foto';
const canvas=$('#photo'),ctx=canvas.getContext('2d',{willReadFrequently:true});
function message(text,error=false){$('#scan-message').textContent=text;$('#scan-message').classList.toggle('error',error);}
function setBusy(value){busy=value;for(const s of ['#camera','#capture','#file','#new','#crop-start','#crop-read','#read-all','#invert'])$(s).disabled=value;$('#qr').disabled=value;$('#ocr').disabled=value;$('#confirmed').disabled=value;$('#progress').hidden=!value;update();}
function update(){const result=inspect($('#qr').value,$('#ocr').value,ocrReliable,$('#confirmed').checked);$('#qr-series').textContent=result.code.serial||'Não identificado';$('#print-series').textContent=result.print.serial||'Não identificado';const style={COINCIDE:'match',DIVERGENTE:'mismatch',PENDENTE:'pending'}[result.status];$('#result').className='result '+style;$('#result .result-symbol').textContent={COINCIDE:'✓',DIVERGENTE:'≠',PENDENTE:'!'}[result.status];$('#result strong').textContent={COINCIDE:'Os 14 caracteres coincidem',DIVERGENTE:'Números de série divergentes',PENDENTE:'Leitura pendente'}[result.status];$('#result p').textContent=result.status==='PENDENTE'?result.reason+' Faça uma nova captura mais próxima.':result.status==='DIVERGENTE'?'Os valores são diferentes. Confira a peça antes de registrar.':'Comparação automática das duas leituras da imagem.';const hasData=!!($('#qr').value.trim()||$('#ocr').value.trim());$('#save').disabled=busy||saving||saved||!storageReady||!hasData;$('#save').textContent=saved?'Comparação registrada':result.status==='PENDENTE'?'Registrar leitura pendente':'Registrar comparação';return result;}
for(const id of ['#qr','#ocr'])$(id).addEventListener('input',()=>{$('#confirmed').checked=false;saved=false;ocrReliable=false;$('#save-message').textContent='';update();});$('#confirmed').addEventListener('change',()=>{saved=false;update();});
function stopCamera(){stream?.getTracks().forEach(t=>t.stop());stream=null;$('#video').srcObject=null;$('#video').hidden=true;$('#capture').hidden=true;$('#stop').hidden=true;$('#camera').hidden=false;if(!photoBase)$('#camera-empty').hidden=false;}
$('#stop').onclick=stopCamera;
$('#camera').onclick=async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('A câmera precisa de HTTPS ou localhost. Use Escolher foto neste aparelho.');stopCamera();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:3840},height:{ideal:2160}},audio:false});const track=stream.getVideoTracks()[0];const caps=track.getCapabilities?.();if(caps?.focusMode?.includes('continuous'))await track.applyConstraints({advanced:[{focusMode:'continuous'}]}).catch(()=>{});const video=$('#video');video.srcObject=stream;await video.play();video.hidden=false;canvas.hidden=true;$('#camera-empty').hidden=true;$('#capture').hidden=false;$('#stop').hidden=false;$('#camera').hidden=true;$('#crop-tools').hidden=true;message('Aproxime a peça, espere o foco estabilizar e toque em Capturar, comparar e registrar.');}catch(error){stopCamera();message(error.name==='NotAllowedError'?'Câmera não autorizada. Permita o acesso no navegador ou escolha uma foto.':error.message,true);}};
function clearReadings(){ocrReliable=false;ocrAttempts=[];codePosition=null;originalCode='';originalOCR='';codeSource='manual';printSource='manual';format='';confidence=null;saved=false;$('#qr').value='';$('#ocr').value='';$('#confirmed').checked=false;$('#code-format').textContent='Aguardando leitura';$('#confidence').textContent='Leitura OCR';$('#save-message').textContent='';update();}
function setPhoto(image,width,height){const scale=Math.min(1,4096/Math.max(width,height));canvas.width=Math.round(width*scale);canvas.height=Math.round(height*scale);ctx.drawImage(image,0,0,canvas.width,canvas.height);photoBase=ctx.getImageData(0,0,canvas.width,canvas.height);canvas.hidden=false;$('#camera-empty').hidden=true;$('#crop-tools').hidden=false;crop=null;cropMode=false;canvas.classList.remove('selecting');$('#crop-read').disabled=true;}
$('#capture').onclick=async()=>{const video=$('#video');if(!video.videoWidth){message('Aguarde a imagem da câmera.',true);return;}clearReadings();captureSource='câmera';setPhoto(video,video.videoWidth,video.videoHeight);stopCamera();await readPhoto(false);};
$('#file').onchange=async(event)=>{const file=event.target.files[0];if(!file)return;stopCamera();clearReadings();captureSource='foto';photoBase=null;canvas.hidden=true;$('#camera-empty').hidden=false;$('#crop-tools').hidden=true;try{const image=await createImageBitmap(file);setPhoto(image,image.width,image.height);image.close();await readPhoto(false);}catch(error){message('Não foi possível abrir a foto. Use uma imagem JPG, PNG ou WebP. '+error.message,true);}finally{event.target.value='';}};
async function ocrWorker(){if(!worker){worker=await createWorker('eng',1,{workerPath:asset('vendor/worker.min.js'),corePath:asset('vendor/'),langPath:asset('vendor/'),logger:info=>{if(info.status==='recognizing text')$('#progress').value=info.progress;}});}return worker;}
function preprocessOCR(context,width,height,invert){const image=context.getImageData(0,0,width,height),data=image.data,hist=new Uint32Array(256);for(let i=0;i<data.length;i+=4){const g=Math.round(.299*data[i]+.587*data[i+1]+.114*data[i+2]);data[i]=g;hist[g]++;}const cutoff=width*height*.02;let low=0,high=255,sum=0;while(low<254&&(sum+=hist[low])<cutoff)low++;sum=0;while(high>low&&(sum+=hist[high])<cutoff)high--;for(let i=0;i<data.length;i+=4){let v=Math.max(0,Math.min(255,(data[i]-low)*255/Math.max(1,high-low)));if(invert)v=255-v;data[i]=data[i+1]=data[i+2]=v;}context.putImageData(image,0,0);}
async function readPhoto(selectionOnly){if(busy||!photoBase)return;setBusy(true);saved=false;$('#confirmed').checked=false;$('#save-message').textContent='';ctx.putImageData(photoBase,0,0);const problems=[];try{
if(!selectionOnly){$('#qr').value='';originalCode='';format='';codeSource=captureSource;$('#code-format').textContent='Procurando código';message('Lendo QR Code / Data Matrix…');try{const codes=(await readBarcodes(photoBase,{formats:['QRCode','DataMatrix'],tryHarder:true,tryInvert:true,maxNumberOfSymbols:8})).filter(c=>c.isValid!==false);if(codes.length===1){originalCode=codes[0].text;$('#qr').value=originalCode;format=codes[0].format;codePosition=codes[0].position;$('#code-format').textContent=format;}else{problems.push(codes.length?'Mais de um código na foto. Fotografe uma peça por vez.':'Código não encontrado. Aproxime a câmera ou use um leitor USB.');$('#code-format').textContent='Não identificado';}}catch{problems.push('Falha ao iniciar o leitor de código. Tente reabrir o aplicativo com internet.');}}
$('#ocr').value='';originalOCR='';confidence=null;ocrReliable=false;ocrAttempts=[];printSource='OCR · '+captureSource;$('#confidence').textContent='Lendo…';message('Localizando e reconhecendo a linha da série…');
try{
  const region=selectionOnly&&crop?crop:nearbyRegion(codePosition,canvas.width,canvas.height);
  ocrAttempts=await readPrintedSerial(canvas,region,text=>message(text),$('#invert').checked);
  const best=selectOCR(ocrAttempts);originalOCR=best.text;confidence=best.confidence;ocrReliable=best.reliable;
  $('#ocr').value=originalOCR;$('#confidence').textContent='OCR · score '+confidence+'/100'+(ocrReliable?' · consistente':' · revisar');
  if(!ocrReliable)problems.push('Tampografia sem leitura confiável. O texto reconhecido será preservado como pendente. Aproxime a câmera ou selecione a linha da série.');
}catch{worker?.terminate();worker=null;$('#confidence').textContent='OCR indisponível';problems.push('Falha no reconhecimento da tampografia. A tentativa será registrada como pendente.');}
message(problems.length?problems.join(' '):'As duas leituras foram comparadas automaticamente.',problems.length>0);
}finally{setBusy(false);crop=null;$('#crop-read').disabled=true;update();}
await persistComparison(true);
}
$('#read-all').onclick=()=>readPhoto(false);$('#crop-read').onclick=()=>readPhoto(true);
$('#crop-start').onclick=()=>{cropMode=true;crop=null;canvas.classList.add('selecting');ctx.putImageData(photoBase,0,0);$('#crop-read').disabled=true;message('Arraste sobre a linha inteira, incluindo NÚMERO DE SÉRIE e todos os caracteres.');};
function point(event){const r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(event.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height,(event.clientY-r.top)*canvas.height/r.height))};}
canvas.onpointerdown=e=>{if(!cropMode||busy)return;start=point(e);canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!start)return;const p=point(e);crop={x:Math.round(Math.min(start.x,p.x)),y:Math.round(Math.min(start.y,p.y)),w:Math.round(Math.abs(p.x-start.x)),h:Math.round(Math.abs(p.y-start.y))};ctx.putImageData(photoBase,0,0);ctx.strokeStyle='#28f4c0';ctx.lineWidth=Math.max(2,canvas.width/350);ctx.strokeRect(crop.x,crop.y,crop.w,crop.h);};canvas.onpointerup=()=>{if(!start)return;start=null;cropMode=false;canvas.classList.remove('selecting');$('#crop-read').disabled=!crop||crop.w<30||crop.h<8;};canvas.onpointercancel=()=>{start=null;crop=null;cropMode=false;canvas.classList.remove('selecting');ctx.putImageData(photoBase,0,0);};
$('#new').onclick=()=>{stopCamera();clearReadings();photoBase=null;canvas.hidden=true;$('#camera-empty').hidden=false;$('#crop-tools').hidden=true;message('Pronto para a próxima peça.');$('#qr').focus();};
function badge(status){const b=document.createElement('span');b.className='badge '+{COINCIDE:'match',DIVERGENTE:'mismatch',PENDENTE:'pending'}[status];b.textContent=status;return b;}
function renderHistory(){$('#count').textContent=records.length;$('#empty-history').hidden=records.length>0;$('#export').disabled=!records.length;$('#more').hidden=records.length<=limit;const body=$('#history');body.replaceChildren();for(const record of records.slice(0,limit)){const tr=document.createElement('tr');for(const value of [new Date(record.date).toLocaleString('pt-BR'),record.codeSerial||'—',record.printSerial||(record.originalOCR?'Texto incerto · ver detalhes':'Não lida')]){const td=document.createElement('td');td.textContent=value;tr.append(td);}const status=document.createElement('td');status.append(badge(record.status));tr.append(status);const td=document.createElement('td');const button=document.createElement('button');button.className='text-button';button.textContent='Ver detalhes';button.onclick=()=>showDetails(record);td.append(button);tr.append(td);body.append(tr);}}
function showDetails(record){const dl=document.createElement('dl');const fields={'Registro':record.id,'Data / hora':new Date(record.date).toLocaleString('pt-BR'),'Resultado':record.status,'Motivo da pendência':record.reason||'—','Registro automático':record.automatic?'Sim':'Não','Passagens do OCR':record.ocrAttempts?.map((a,i)=>'Leitura '+(i+1)+' · '+(a.model||'Tesseract')+' · '+(a.variant||a.mode||'')+' ('+a.confidence+'%): '+a.text).join('\n\n')||'Não disponíveis','Série no código':record.codeSerial||'Não identificada','Série na tampografia':record.printSerial||'Não identificada','Código original':record.originalCode||'(entrada manual)','Código utilizado':record.qr,'Texto OCR original':record.originalOCR||'(sem OCR)','Texto da tampografia utilizado':record.ocr,'Formato':record.format||'Manual','Confiança OCR':record.confidence===null?'Não disponível':record.confidence+'%','Origem':`${record.codeSource} / ${record.printSource}`,'Correções manuais':`Código: ${record.codeEdited?'sim':'não'} · Tampografia: ${record.printEdited?'sim':'não'}`,'Conferência visual':record.confirmed?'Confirmada pelo operador':'Não confirmada','Regra':record.rule};for(const [key,value]of Object.entries(fields)){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;dl.append(dt,dd);}$('#detail-body').replaceChildren(dl);$('#details').showModal();}
$('#close-details').onclick=()=>$('#details').close();$('#more').onclick=()=>{limit+=50;renderHistory();};
async function persistComparison(automatic=false){
if(saving||saved||!storageReady){if(!storageReady)$('#save-message').textContent='Histórico indisponível. Esta captura ainda não foi salva.';return;}
if(!automatic&&$('#save').disabled)return;
const result=update();
const record={id:crypto.randomUUID(),date:new Date().toISOString(),status:result.status,reason:result.reason,rawComparison:result.rawComparison,automatic,ocrReliable,ocrAttempts,codeSerial:result.code.serial,printSerial:result.print.serial,qr:$('#qr').value,ocr:$('#ocr').value,originalCode,originalOCR,codeSource,printSource,format,confidence,codeEdited:$('#qr').value!==originalCode,printEdited:$('#ocr').value!==originalOCR,confirmed:$('#confirmed').checked,rule:RULE+' / camera-v3-paddle'};
saving=true;update();
try{await saveRecord(record);saved=true;$('#save-message').textContent=(automatic?'Captura registrada automaticamente: ':'Registro salvo: ')+record.status+'.';records=await listRecords();renderHistory();}
catch{$('#save-message').textContent='Não foi possível confirmar o salvamento. Confira o histórico antes de tentar novamente.';}
finally{saving=false;update();}
}
$('#save').onclick=()=>persistComparison(false);
$('#export').onclick=()=>{const blob=new Blob([csv(records)],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`valida-laser-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function init(){try{records=await listRecords();storageReady=true;renderHistory();}catch{$('#storage-status').textContent='Armazenamento indisponível';$('#save-message').textContent='Este navegador não permitiu salvar o histórico. Use uma janela normal com armazenamento habilitado.';}update();if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;$('#offline-state').textContent=navigator.onLine?'Pronto para uso offline':'Modo offline';}catch{$('#offline-state').textContent='Offline indisponível';}}}
let installPrompt;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#install').hidden=false;});$('#install').onclick=async()=>{await installPrompt?.prompt();installPrompt=null;$('#install').hidden=true;};window.addEventListener('pagehide',stopCamera);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();});init();
try{document.modelContext?.registerTool({name:'read_comparison_summary',description:'Lê a comparação atual e a quantidade de registros locais. Não salva nem altera dados.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||Object.keys(input).length)throw new Error('Não são aceitos parâmetros.');return {comparison:inspect($('#qr').value,$('#ocr').value,ocrReliable,$('#confirmed').checked),recordCount:records.length};}});}catch{}
