import {comparePositions,usesProfile} from './serial-profile.mjs';
export const RULE='serial-positions-gh44-v4';
const label=/(?:N[ÚUÜO]MERO\s*DE\s*S[ÉE]RIE|SERIAL(?:\s*(?:NUMBER|NO))?|S\/N|SN)\s*[:=]\s*([A-Za-z0-9]+)/gi;
const tail=value=>typeof value==='string'&&/^[A-Za-z0-9]{14,}$/.test(value)?value.slice(-14):null;
const exact=value=>typeof value==='string'&&/^[A-Za-z0-9]{14}$/.test(value)?value:null;
function labelled(text){return [...text.matchAll(new RegExp(label))].map(m=>m[1]);}
function uniqueSerial(values){const valid=values.map(tail);return valid.length&&valid.every(Boolean)&&new Set(valid).size===1?valid[0]:null;}
export function extractPrint(raw){const values=labelled(raw);if(values.length)return {serial:values.length===1?exact(values[0]):uniqueSerial(values.map(exact)),reason:'A série após : precisa ter exatamente 14 letras/números e ser inequívoca.'};const afterColon=[...raw.matchAll(/[:=]\s*([A-Za-z0-9]+)/g)].map(m=>m[1]);return {serial:afterColon.length===1?exact(afterColon[0]):null,reason:'Não foi encontrada uma única série de 14 caracteres após : no texto.'};}
export function extractCode(raw){const text=raw.trim();if(!text)return {serial:null,reason:'Leia o código 2D.'};const tagged=labelled(text);if(tagged.length)return {serial:uniqueSerial(tagged),method:'Campo de série'};
try{const obj=JSON.parse(text);if(obj&&typeof obj==='object'&&!Array.isArray(obj)){const values=Object.entries(obj).filter(([k])=>/^(sn|serial|serialnumber|serial_number|numero_?serie|numero_?de_?serie)$/i.test(k)).map(([,v])=>typeof v==='string'?v:'');return {serial:uniqueSerial(values),method:'Campo JSON'};}}catch{}
try{const u=new URL(text);const values=[...u.searchParams].filter(([k])=>/^(sn|serial|serialnumber|serial_number|numero_?serie)$/i.test(k)).map(([,v])=>v);return {serial:uniqueSerial(values),method:'Parâmetro da URL'};}catch{}
if(text.includes('+')){const partSerial=text.match(/^[A-Za-z0-9-]+\+([A-Za-z0-9]+)$/);return {serial:partSerial?exact(partSerial[1]):null,method:'Série após +',reason:'A série após + precisa ter exatamente 14 letras/números.'};}
const gs1=text.match(/(?:\(21\)|\x1d21)([A-Za-z0-9]+)(?:\x1d|$)/);if(gs1)return {serial:tail(gs1[1]),method:'GS1 (21)'};
return {serial:tail(text),method:'Conteúdo alfanumérico · 14 finais',reason:'Conteúdo sem uma série inequívoca. Use um código alfanumérico ou um campo de série identificado.'};}
export function compare(qr,ocr){const code=extractCode(qr),print=extractPrint(ocr);const profile=usesProfile(qr)&&code.serial&&print.serial?comparePositions(code.serial,print.serial):null;return {code,print,profile,status:!code.serial||!print.serial?'PENDENTE':code.serial===print.serial?'COINCIDE':'DIVERGENTE'};}
export function csv(records){const headings=['ID','Data UTC','Data local','Inspetor','Turno informado','Sincronizacao','Resultado','Serie codigo 14 finais','Serie tampografia 14 finais','Codigo completo original','Codigo utilizado','Texto OCR original','Texto tampografia utilizado','Formato codigo','Confianca OCR','Origem codigo','Origem tampografia','Codigo editado','Tampografia editada','Conferencia visual','Regra','Registro automatico','Motivo pendencia','Passagens OCR'];const cell=v=>'"'+String(v??'').replace(/^[\s]*[=+@-]/,m=>"'"+m).replaceAll('"','""')+'"';return '\ufeff'+[headings,...records.map(r=>[r.id,r.date,new Date(r.date).toLocaleString('pt-BR'),r.inspector,r.shift||'',r.syncState,r.status,r.codeSerial,r.printSerial,r.originalCode,r.qr,r.originalOCR,r.ocr,r.format,r.confidence,r.codeSource,r.printSource,r.codeEdited,r.printEdited,r.confirmed,r.rule,r.automatic,r.reason,JSON.stringify(r.ocrAttempts||[])])].map(row=>row.map(cell).join(';')).join('\r\n');}
