export const RULE='serial-last14-v1';
const label=/(?:N[ÚUÜO]MERO\s*DE\s*S[ÉE]RIE|SERIAL(?:\s*(?:NUMBER|NO))?|S\/N|SN)\s*[:=]\s*([A-Za-z0-9]+)/gi;
const tail=value=>typeof value==='string'&&/^[A-Za-z0-9]{14,}$/.test(value)?value.slice(-14):null;
function labelled(text){return [...text.matchAll(new RegExp(label))].map(m=>m[1]);}
function uniqueSerial(values){const valid=values.map(tail);return valid.length&&valid.every(Boolean)&&new Set(valid).size===1?valid[0]:null;}
export function extractPrint(raw){const values=labelled(raw);return {serial:uniqueSerial(values),reason:values.length?'A série precisa ter pelo menos 14 letras/números contínuos e ser inequívoca.':'Não foi encontrada a indicação NÚMERO DE SÉRIE: no texto.'};}
export function extractCode(raw){const text=raw.trim();if(!text)return {serial:null,reason:'Leia o código 2D.'};const tagged=labelled(text);if(tagged.length)return {serial:uniqueSerial(tagged),method:'Campo de série'};
try{const obj=JSON.parse(text);if(obj&&typeof obj==='object'&&!Array.isArray(obj)){const values=Object.entries(obj).filter(([k])=>/^(sn|serial|serialnumber|serial_number|numero_?serie|numero_?de_?serie)$/i.test(k)).map(([,v])=>typeof v==='string'?v:'');return {serial:uniqueSerial(values),method:'Campo JSON'};}}catch{}
try{const u=new URL(text);const values=[...u.searchParams].filter(([k])=>/^(sn|serial|serialnumber|serial_number|numero_?serie)$/i.test(k)).map(([,v])=>v);return {serial:uniqueSerial(values),method:'Parâmetro da URL'};}catch{}
const partSerial=text.match(/^[A-Za-z0-9-]+\+([A-Za-z0-9]{14,})$/);if(partSerial)return {serial:tail(partSerial[1]),method:'Código da peça + série'};
const gs1=text.match(/(?:\(21\)|\x1d21)([A-Za-z0-9]+)(?:\x1d|$)/);if(gs1)return {serial:tail(gs1[1]),method:'GS1 (21)'};
return {serial:tail(text),method:'Conteúdo alfanumérico · 14 finais',reason:'Conteúdo sem uma série inequívoca. Use um código alfanumérico ou um campo de série identificado.'};}
export function compare(qr,ocr){const code=extractCode(qr),print=extractPrint(ocr);return {code,print,status:!code.serial||!print.serial?'PENDENTE':code.serial===print.serial?'COINCIDE':'DIVERGENTE'};}
export function csv(records){const headings=['ID','Data UTC','Data local','Resultado','Serie codigo 14 finais','Serie tampografia 14 finais','Codigo completo original','Codigo utilizado','Texto OCR original','Texto tampografia utilizado','Formato codigo','Confianca OCR','Origem codigo','Origem tampografia','Codigo editado','Tampografia editada','Conferencia visual','Regra','Registro automatico','Motivo pendencia','Passagens OCR'];const cell=v=>'"'+String(v??'').replace(/^[\s]*[=+@-]/,m=>"'"+m).replaceAll('"','""')+'"';return '\ufeff'+[headings,...records.map(r=>[r.id,r.date,new Date(r.date).toLocaleString('pt-BR'),r.status,r.codeSerial,r.printSerial,r.originalCode,r.qr,r.originalOCR,r.ocr,r.format,r.confidence,r.codeSource,r.printSource,r.codeEdited,r.printEdited,r.confirmed,r.rule,r.automatic,r.reason,JSON.stringify(r.ocrAttempts||[])])].map(row=>row.map(cell).join(';')).join('\r\n');}
